In [1]:
import torch

In [4]:
default = torch.tensor([1.5, 2.5, 3.5])
print(default.dtype)

torch.float32


In [6]:
float_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [7]:
int_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [8]:
int_tensor = torch.tensor([1, 2, 3])
print(int_tensor.dtype)
print(int_tensor)

torch.int64
tensor([1, 2, 3])


In [9]:
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.bool
tensor([ True, False,  True])


In [10]:
float_tensor = torch.tensor([1.5, 2.5, 3.5])
print(float_tensor.dtype)
print(float_tensor)

int_tensor = float_tensor.to(torch.int64)
print(int_tensor.dtype)
print(int_tensor)

int_tensor = torch.tensor([0,1,2,0, -1])
bool_tensor = int_tensor.to(torch.bool)
print(bool_tensor.dtype)
print(bool_tensor)

torch.float32
tensor([1.5000, 2.5000, 3.5000])
torch.int64
tensor([1, 2, 3])
torch.bool
tensor([False,  True,  True, False,  True])


In [11]:
float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)

# tensor.element_size()
# element_size() --> gives you the size of one element in bytes
# nelement() --> gives the total number of elements in tensor

print(float32_tensor.element_size())
print(float32_tensor.nelement())
print("Memory used by float32 tensor : ", float32_tensor.element_size() * float32_tensor.nelement(), " bytes")
print("Memory used by float64 tensor : ", float64_tensor.element_size() * float64_tensor.nelement(), " bytes")

4
1000
Memory used by float32 tensor :  4000  bytes
Memory used by float64 tensor :  8000  bytes
